---
- hosts: localhost
  vars_files:
    - settings.yml
    - ['~/cloudbox/accounts.yml', '~/cloudbox/defaults/accounts.yml.default']
    - ['~/cloudbox/settings.yml', '~/cloudbox/defaults/settings.yml.default']
    - ['~/cloudbox/adv_settings.yml', '~/cloudbox/defaults/adv_settings.yml.default']

  roles:
    - { role: pre_tasks, tags: ['pre_tasks'] }
    - { role: cloudcmd, tags: ['cloudcmd'] }
